#!/bin/sh

if [ "$#" -ne 1 ]; then
    echo -e "Please enter the project name. (Note: \033[1;33mNote: It must be composed of letters, numbers or underscores.\033[0m)" >&2
    exit 1
fi

project_name=$1
project_dir="/var/svn/repos/$project_name"

if [ -d "$project_dir" ]; then
    echo -e "\033[1;31mError: Project ${project_name} already exists." >&2
    exit 2
fi

/usr/bin/svnadmin create $project_dir

rm -f $project_dir/conf/authz
rm -f $project_dir/conf/passwd
rm -f $project_dir/conf/svnserve.conf

exit 0
